/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package POSTTEST3;

import POSTTEST3.BIODATA;
import POSTTEST3.SCHOOLARSHIP;
import javax.swing.JOptionPane;

/**
 *
 * @author SMAZ
 */
public class POSTTEST3 extends javax.swing.JFrame {

    /**
     * Creates new form tugas
     */
    public POSTTEST3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelhome = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelformulir = new javax.swing.JPanel();
        Biodata1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        btnReset5 = new javax.swing.JButton();
        btnSave5 = new javax.swing.JButton();
        txtNama5 = new javax.swing.JTextField();
        txtNim5 = new javax.swing.JTextField();
        radMale5 = new javax.swing.JRadioButton();
        radFemale5 = new javax.swing.JRadioButton();
        CboxSchool5 = new javax.swing.JComboBox();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtaAddres5 = new javax.swing.JTextArea();
        CboxCity5 = new javax.swing.JComboBox();
        ChboxMobil5 = new javax.swing.JCheckBox();
        ChboxSepeda5 = new javax.swing.JCheckBox();
        ChboxMotor5 = new javax.swing.JCheckBox();
        ChboxBajai5 = new javax.swing.JCheckBox();
        jPanel13 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        Biodata2 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtaTampil = new javax.swing.JTextArea();
        panelvisi = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panelmisi = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelabout = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        formulir = new javax.swing.JButton();
        visi = new javax.swing.JButton();
        misi = new javax.swing.JButton();
        biodata = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setLayout(new java.awt.CardLayout());

        panelhome.setBackground(new java.awt.Color(255, 204, 51));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("Selamat Datang!!!");

        javax.swing.GroupLayout panelhomeLayout = new javax.swing.GroupLayout(panelhome);
        panelhome.setLayout(panelhomeLayout);
        panelhomeLayout.setHorizontalGroup(
            panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelhomeLayout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(199, 199, 199))
        );
        panelhomeLayout.setVerticalGroup(
            panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhomeLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel7)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jPanel1.add(panelhome, "card3");

        panelformulir.setBackground(new java.awt.Color(255, 204, 51));
        panelformulir.setLayout(new java.awt.CardLayout());

        Biodata1.setBackground(new java.awt.Color(255, 204, 51));

        jPanel7.setBackground(new java.awt.Color(255, 51, 51));
        jPanel7.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel7.setForeground(new java.awt.Color(255, 204, 51));

        jLabel18.setText("Nama");

        jLabel47.setText("Nim");

        jLabel48.setText("Sex");

        jLabel49.setText("SCHOOLARSHIP");

        jLabel50.setText("Address");

        jLabel51.setText("City");

        jLabel52.setText("Transportation");

        btnReset5.setText("Reset");
        btnReset5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset5ActionPerformed(evt);
            }
        });

        btnSave5.setText("Save");
        btnSave5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave5ActionPerformed(evt);
            }
        });

        txtNim5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNim5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radMale5);
        radMale5.setText("Male");

        buttonGroup1.add(radFemale5);
        radFemale5.setText("Female");

        CboxSchool5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Regular", "Smart Type", "Needy", "Research" }));

        txtaAddres5.setColumns(20);
        txtaAddres5.setRows(5);
        jScrollPane6.setViewportView(txtaAddres5);

        CboxCity5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Samarinda", "Bontang", "Panajam", "Balikpapan", "PPU" }));

        ChboxMobil5.setText("Mobil");
        ChboxMobil5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChboxMobil5ActionPerformed(evt);
            }
        });

        ChboxSepeda5.setText("Sepeda");

        ChboxMotor5.setText("Motor");

        ChboxBajai5.setText("Bajai");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReset5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave5))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel50)
                                    .addComponent(jLabel51))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(CboxCity5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane6))))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel49)
                                    .addComponent(jLabel48)
                                    .addComponent(jLabel47)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addComponent(radFemale5))
                                    .addComponent(radMale5)
                                    .addComponent(CboxSchool5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNim5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNama5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addGap(18, 18, 18)
                                .addComponent(ChboxMobil5)
                                .addGap(18, 18, 18)
                                .addComponent(ChboxSepeda5)
                                .addGap(18, 18, 18)
                                .addComponent(ChboxMotor5)
                                .addGap(18, 18, 18)
                                .addComponent(ChboxBajai5)))
                        .addGap(0, 329, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtNama5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(txtNim5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(radMale5)
                    .addComponent(radFemale5))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(CboxSchool5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel50)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel51))
                    .addComponent(CboxCity5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(ChboxMobil5)
                    .addComponent(ChboxSepeda5)
                    .addComponent(ChboxMotor5)
                    .addComponent(ChboxBajai5))
                .addGap(41, 41, 41)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset5)
                    .addComponent(btnSave5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 102));
        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel53.setText("Daftar");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel53)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel53)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Biodata1Layout = new javax.swing.GroupLayout(Biodata1);
        Biodata1.setLayout(Biodata1Layout);
        Biodata1Layout.setHorizontalGroup(
            Biodata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Biodata1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Biodata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Biodata1Layout.setVerticalGroup(
            Biodata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Biodata1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelformulir.add(Biodata1, "card2");

        Biodata2.setBackground(new java.awt.Color(255, 204, 51));

        jPanel14.setBackground(new java.awt.Color(255, 51, 255));
        jPanel14.setBorder(new javax.swing.border.MatteBorder(null));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtaTampil.setColumns(20);
        txtaTampil.setRows(5);
        jScrollPane7.setViewportView(txtaTampil);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(285, 285, 285))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Biodata2Layout = new javax.swing.GroupLayout(Biodata2);
        Biodata2.setLayout(Biodata2Layout);
        Biodata2Layout.setHorizontalGroup(
            Biodata2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Biodata2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Biodata2Layout.setVerticalGroup(
            Biodata2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Biodata2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelformulir.add(Biodata2, "card3");

        jPanel1.add(panelformulir, "card4");

        panelvisi.setBackground(new java.awt.Color(255, 204, 51));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("VISI :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Menjadi kan Fakultas yang bertaraf International");

        javax.swing.GroupLayout panelvisiLayout = new javax.swing.GroupLayout(panelvisi);
        panelvisi.setLayout(panelvisiLayout);
        panelvisiLayout.setHorizontalGroup(
            panelvisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelvisiLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        panelvisiLayout.setVerticalGroup(
            panelvisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelvisiLayout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addGroup(panelvisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addGap(204, 204, 204))
        );

        jPanel1.add(panelvisi, "card5");

        panelmisi.setBackground(new java.awt.Color(255, 204, 51));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setText("MISI :");

        jLabel11.setText("Menciptakan Fakultas yang BERIMAN (Bersih,Indah,Aman dan Nyaman) dari segala perpecahan dan segala hal yang akan ");

        jLabel12.setText("terjadi di muka bumi ini.");

        javax.swing.GroupLayout panelmisiLayout = new javax.swing.GroupLayout(panelmisi);
        panelmisi.setLayout(panelmisiLayout);
        panelmisiLayout.setHorizontalGroup(
            panelmisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmisiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelmisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addContainerGap())
        );
        panelmisiLayout.setVerticalGroup(
            panelmisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmisiLayout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addGroup(panelmisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelmisiLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addComponent(jLabel9))
                .addGap(206, 206, 206))
        );

        jPanel1.add(panelmisi, "card6");

        panelabout.setBackground(new java.awt.Color(255, 204, 51));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Biodata");

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer-pc\\Documents\\Syamsudi.png")); // NOI18N

        jLabel15.setText("Nama   :");

        jLabel16.setText("Kelas    : ");

        jLabel17.setText("Nim      :");

        jLabel19.setText("Syamsudin hadi");

        jLabel20.setText("D 2015");

        jLabel21.setText("1515015189");

        javax.swing.GroupLayout panelaboutLayout = new javax.swing.GroupLayout(panelabout);
        panelabout.setLayout(panelaboutLayout);
        panelaboutLayout.setHorizontalGroup(
            panelaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelaboutLayout.createSequentialGroup()
                .addGroup(panelaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelaboutLayout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel10))
                    .addGroup(panelaboutLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel14)
                        .addGap(35, 35, 35)
                        .addGroup(panelaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(panelaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        panelaboutLayout.setVerticalGroup(
            panelaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelaboutLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel10)
                .addGap(49, 49, 49)
                .addGroup(panelaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelaboutLayout.createSequentialGroup()
                        .addGroup(panelaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel20))
                        .addGap(49, 49, 49)
                        .addGroup(panelaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel21)))
                    .addComponent(jLabel14))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        jPanel1.add(panelabout, "card7");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistem Informasi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fakultas Ilmu Komputer dan Teknologi Informasi");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer-pc\\Downloads\\AS 267467136405507@1440780542223_m.png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer-pc\\Downloads\\pngg.png")); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 255, 102));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel6.add(home);

        formulir.setText("Isi Formulir");
        formulir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formulirActionPerformed(evt);
            }
        });
        jPanel6.add(formulir);

        visi.setText("Visi");
        visi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visiActionPerformed(evt);
            }
        });
        jPanel6.add(visi);

        misi.setText("Misi");
        misi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misiActionPerformed(evt);
            }
        });
        jPanel6.add(misi);

        biodata.setText("About");
        biodata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biodataActionPerformed(evt);
            }
        });
        jPanel6.add(biodata);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(148, 148, 148)))
                .addComponent(jLabel3)
                .addGap(44, 44, 44))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("MODUL PRAKTIKUM PEMROGRAMAN VISUAL");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("@Copyright");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(227, 227, 227))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(332, 332, 332))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        panelhome.setVisible(true);
        panelformulir.setVisible(false);
        panelvisi.setVisible(false);
        panelmisi.setVisible(false);
        panelabout.setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    private void formulirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formulirActionPerformed
        // TODO add your handling code here:
        panelhome.setVisible(false);
        panelformulir.setVisible(true);
        panelvisi.setVisible(false);
        panelmisi.setVisible(false);
        panelabout.setVisible(false);
        
    }//GEN-LAST:event_formulirActionPerformed

    private void visiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visiActionPerformed
        // TODO add your handling code here:
        panelhome.setVisible(false);
        panelformulir.setVisible(false);
        panelvisi.setVisible(true);
        panelmisi.setVisible(false);
        panelabout.setVisible(false);
    }//GEN-LAST:event_visiActionPerformed

    private void misiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misiActionPerformed
        // TODO add your handling code here:
        panelhome.setVisible(false);
        panelformulir.setVisible(false);
        panelvisi.setVisible(false);
        panelmisi.setVisible(true);
        panelabout.setVisible(false);
    }//GEN-LAST:event_misiActionPerformed

    private void biodataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biodataActionPerformed
        // TODO add your handling code here:
        panelhome.setVisible(false);
        panelformulir.setVisible(false);
        panelvisi.setVisible(false);
        panelmisi.setVisible(false);
        panelabout.setVisible(true);
    }//GEN-LAST:event_biodataActionPerformed

    private void btnReset5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset5ActionPerformed
        // TODO add your handling code here:
        txtNama5.setText("");
        txtNim5.setText("");
        txtaAddres5.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnReset5ActionPerformed

    private void btnSave5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave5ActionPerformed
        // TODO add your handling code here:

        String Nama,Nim,School,Addres,City;
        try{
            if(txtNama5.getText().length()==0){
                JOptionPane.showMessageDialog(null, "jangan kosong tio mas");
            }else{
                Nama = txtNama5.getText();
                Nim = txtNim5.getText();
                String Sex = null;
                if(radMale5.isSelected()){
                    Sex = radMale5.getText();
                }else if (radFemale5.isSelected()){
                    Sex = radFemale5.getText();
                }
                School = (String) CboxSchool5.getSelectedItem().toString();
                Addres = txtaAddres5.getText();
                City = (String) CboxCity5.getSelectedItem().toString();
                String Tansportation = null;
                if (ChboxMobil5.isSelected()){
                    Tansportation = ChboxMobil5.getText();
                }else if (ChboxMotor5.isSelected()){
                    Tansportation = ChboxMotor5.getText();
                }else if (ChboxSepeda5.isSelected()){
                    Tansportation = ChboxSepeda5.getText();
                }else if (ChboxBajai5.isSelected()){
                    Tansportation = ChboxBajai5.getText();
                }

                BIODATA Biodata = new BIODATA (Nama,Nim,Sex,School,Addres,City,Tansportation);
                Biodata.setVisible(true);
                dispose();               
            }
        }catch(Error e){
            System.out.print("Error");
        }

    }//GEN-LAST:event_btnSave5ActionPerformed

    private void ChboxMobil5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChboxMobil5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChboxMobil5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        POSTTEST3 pos = new POSTTEST3();
        pos.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNim5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNim5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNim5ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POSTTEST3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POSTTEST3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POSTTEST3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POSTTEST3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POSTTEST3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Biodata1;
    private javax.swing.JPanel Biodata2;
    private javax.swing.JComboBox CboxCity5;
    private javax.swing.JComboBox CboxSchool5;
    private javax.swing.JCheckBox ChboxBajai5;
    private javax.swing.JCheckBox ChboxMobil5;
    private javax.swing.JCheckBox ChboxMotor5;
    private javax.swing.JCheckBox ChboxSepeda5;
    private javax.swing.JButton biodata;
    private javax.swing.JButton btnReset5;
    private javax.swing.JButton btnSave5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton formulir;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton misi;
    private javax.swing.JPanel panelabout;
    private javax.swing.JPanel panelformulir;
    private javax.swing.JPanel panelhome;
    private javax.swing.JPanel panelmisi;
    private javax.swing.JPanel panelvisi;
    private javax.swing.JRadioButton radFemale5;
    private javax.swing.JRadioButton radMale5;
    private javax.swing.JTextField txtNama5;
    private javax.swing.JTextField txtNim5;
    private javax.swing.JTextArea txtaAddres5;
    private javax.swing.JTextArea txtaTampil;
    private javax.swing.JButton visi;
    // End of variables declaration//GEN-END:variables
}
